# Generated by Django 6.0.4 on 2026-05-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_socialmedialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
