# Generated by Django 6.0.4 on 2026-04-25 18:11

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEOMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceo_name', models.CharField(max_length=200)),
                ('ceo_title', models.CharField(max_length=200)),
                ('ceo_photo', cloudinary.models.CloudinaryField(max_length=255)),
                ('quote', models.TextField()),
                ('body_text', models.TextField()),
                ('tagline', models.CharField(max_length=200)),
                ('sub_tagline', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CEO Message',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='team_photos/')),
                ('bio', models.TextField()),
            ],
        ),
    ]
