# Generated by Django 6.0.4 on 2026-05-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_teammember_github_url_teammember_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
