# Generated by Django 6.0.4 on 2026-05-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=255)),
                ('author_title', models.CharField(blank=True, max_length=255)),
                ('author_profile_image', models.ImageField(blank=True, null=True, upload_to='product/testimonials/')),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='product.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
