# Generated by Django 6.0.4 on 2026-05-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpost_is_active_remove_comment_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['order', 'published_date']},
        ),
    ]
